#!/bin/bash

declare -A statuses

CONTAINERS=$(docker ps | grep -v NAMES | grep -v k8s | awk '{print $NF}')
if [ -n "$CONTAINERS" ]; then
  while read -r line; do
      statuses[$line]="a"
  done <<< "$CONTAINERS"
fi

len=${#statuses[@]}
if [ "$len" -eq "0" ]; then
  printf '\n'
  exit 1
fi

sorted=()
while IFS= read -rd '' key; do
    sorted+=( "$key" )
done < <(printf '%s\0' "${!statuses[@]}" | sort -z)


LIST=" "
TAB=' '
count="0"
for key in "${sorted[@]}"; do
    if [ "${statuses[$key]}" == "a" ]; then
      CONTAINER=" "
      CONTAINER="$CONTAINER$key "
    fi
    if [ "$count" -eq "0" ]; then
      count="1"
    else
      CONTAINER="${TAB}"$CONTAINER
    fi
    LIST=$LIST$CONTAINER
done

printf '%s  \n' "$LIST"


