#!/bin/bash

declare -A statuses

CONTAINERS=$(docker ps | grep -v NAMES | grep -v k8s | awk '{print $NF}')
if [ -n "$CONTAINERS" ]; then
  while read -r line; do
      statuses[$line]="a"
  done <<< "$CONTAINERS"
fi

CONTAINERS=$(docker ps -f "status=exited" | grep -v NAMES | grep -v k8s | awk '{print $NF}')
if [ -n "$CONTAINERS" ]; then
  while read -r line; do
      statuses["$line"]="e"
    done <<< "$CONTAINERS"
fi

len=${#statuses[@]}
if [ "$len" -eq "0" ]; then
  printf '\n'
  exit 1
fi

sorted=()
while IFS= read -rd '' key; do
    sorted+=( "$key" )
done < <(printf '%s\0' "${!statuses[@]}" | sort -z)


LIST=""
for key in "${sorted[@]}"; do
    if [ "${statuses[$key]}" == "a" ]; then
      echo '${color b8bb26}↑ ${color d8dee9}'$key
    else
      echo '${color fb4934}↓ ${color d8dee9}'$key
    fi
    LIST=$LIST$CONTAINER
done



